CREATE TABLE IF NOT EXISTS public.users (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1
    ),
    -- user details
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text UNIQUE,
    password text NOT NULL,
    role text,
    -- configuration
    active boolean,
    confirmation_otp text,
    otp_updated_at timestamp,
    reset_password text,
    number_of_verification_attempts int,
    user_ip text,
    valid_from date,
    valid_to date,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_modified_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by text,
    last_modified_by text,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
ALTER TABLE public.users OWNER to postgres;